### ISSUE TITLE
small annoyance in configure.ac

### ISSUE THREAD

**Issue by kiwifb** [JohnCremona/eclib#15]
I tried to produce a bzip2 tarball of eclib-20160206 for https://trac.sagemath.org/ticket/20928 and then after starting work I realised that the tarball produced by `make dist-bzip2` was named eclib-20160101.tar.bz2 and was unfolding in `eclib-2160101` instead of the expected `20160206`. I am guessing that's because you didn't change line of `configure.ac`:
```
AC_INIT([eclib], [20160101], [john.cremona@gmail.com])
```
before making the release. 
https://github.com/JohnCremona/eclib/blob/v20160206/configure.ac

**Comment by JohnCremona** [comment]
Sorry about that.  My current local repository has version [20160426] in configure.ac and that is what is the HEAD of teh master branch on github, but I did not then make a new release.  Looking at the git log it seems that this version has several small revisions relevant to making compatible with c++-11, so I presume it would be most helpful to you to make a new release tarball from that?  There is also an outstanding pull request from someone I don't know but it will require some merge conflict resolution.

**Comment by kiwifb** [comment]
Yes it would probably be most helpful to get a new release with all the current available fixes. It shouldn't be too hard to solve the PR conflict, but in the absence of a reaction from its author, it will have to be done manually I think.

**Comment by JohnCremona** [comment]
I'll see if I can resolve the conflict, and wither way make a new release today.

**Comment by JohnCremona** [comment]
OK, I merged the other Pull Request and updated configure.ac so that the release number is 20160720, also incremented the library revision number, and made a new release.

**Comment by kiwifb** [comment]
OK, github is doing something weird. The tarball `eclib-20160720.tar.gz` from github doesn't contain the commit https://github.com/JohnCremona/eclib/commit/186c37c72f11ecedd7818bfd6e69c876decd6441
even thought it says it was created at that point and https://github.com/JohnCremona/eclib/blob/20160720/configure.ac is correct.

**Comment by kiwifb** [comment]
OK the weirdness is on me. I download a different tarball with my browser on my mac laptop than with my gentoo ebuild on my linux box. It must be doing something wrong but it is not your fault at least.

**Comment by kiwifb** [comment]
For the curious: I used to fetch `v20160720.tar.gz` because some older release had the leading `v`. That `v` is not part of the tarball name on github but obviously you still fetch "something" with it.

**Comment by JohnCremona** [comment]
Yes, I don't know wht the Releases page at https://github.com/JohnCremona/eclib/releases has tarballs which are not the ones for actual releases!  But the top release listed there does have the correct tarball.

**Comment by kiwifb** [comment]
Yes and that wasn't the one I was fetching. I would have much preferred for the download to fail, so I would have known I was trying to pull the wrong thing, rather than getting "something".
