### ISSUE TITLE
Make hecke operators not blow up the memory

### ISSUE THREAD

**Issue by kartikv** [JohnCremona/eclib#17]
Constructing Hecke operators acting on modular symbols can blow up the memory usage, though it doesn't have to. In Cremona's code, there's a function calcop which covers the main computation:
`
  mat m(rk,rk);
  for (long j=0; j<rk; j++) if (needed[j])
     { svec colj = applyop(mlist,freemods[j]);
       m.setcol(j+1,colj.as_vec());
     }
  if(cuspidal) m = restrict_mat(smat(m),kern).as_mat();
`
Note that this code correctly the columns as sparse vectors, but then inserts them into a dense matrix: then, if the form is cuspidal, it actually converts it to a sparse matrix, does the restriction, and converts it back to a dense matrix.

Recommendation: have this (or another, similarly named function) do this entirely with sparse matrices, so that the memory stays minimal

**Comment by kartikv** [comment]
Sorry, there totally is another function that does this, just not called by sage.

**Comment by JohnCremona** [comment]
I suppose that I should clear out some obsolete functions from this code.
Meanwhile feel free to work on the Sage interface, which is lacking in a
lot of functionality.
