### ISSUE TITLE
typo in xsplit.cc ?

### ISSUE THREAD

**Issue by dimpase** [JohnCremona/eclib#21]
compiling with clang 4.0.1 I see
```
xsplit.cc:299:24: warning: use of unary operator that may be intended as compound assignment (-=)
    if(signeig<0) seig =- eig;
```
You might like to adjust spacing---assuming there it is meant to be `...= -eig`

**Comment by JohnCremona** [comment]
Of course I mean seig = -eig.
If you care, send a pull request.

**Comment by dimpase** [comment]
see https://github.com/JohnCremona/eclib/pull/22
