### ISSUE TITLE
eclib includes must be included in a specific order

### ISSUE THREAD

**Issue by jdemeyer** [JohnCremona/eclib#30]
From `src/sage/libs/eclib/__init__.pxd` in Sage:
```
# NOTE: eclib includes have specific dependencies and must be included
# in a specific order. That explains the various empty
# "cdef extern from" blocks below.
```

There is quite a bit black magic involved in getting the eclib include order correct. Ideally, every `.h` file should be self-contained in the sense that it `#include`s everything which is needed to parse that file. To give one example, `homspace.h` starts with
```
class homspace :public symbdata {
```
However, `symbdata` is not declared in this header file. So if one only does `#include "homspace.h"`, you will get compiler errors.

**Comment by JohnCremona** [comment]
It's a good idea certainly, though would be rather tedious to implement.

**Comment by jdemeyer** [comment]
Sure. This isn't something that urgently needs to be fixed. It's something to keep in your mind in case you are making changes anyway.

**Comment by JohnCremona** [comment]
Fixed in v20180710.  Now each include file may be #include'd by itself.  In the docs directory is a file showing which include files include which others, for reference.
