### ISSUE TITLE
Version 20171219 has test failures on i386

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/eclib#36]
Hi,

I got the following report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892139

where all failures look like the result gives more digits than what is expected.

Cheers,

**Comment by JohnCremona** [comment]
This is probably caused by some changes being made to try to fix Issue #19  (see also PR #35).

I am beginning to think that the only way I will ever get any peace is to delete all tests which have any floating point output.

**Comment by SnarkBoojum** [comment]
I think the best with floats is to do things like:
```
    if (abs(function(arguments)-expected) >= eps) {
        
        <output a nice error message>
    } else {
        
        <output a nice non-error message>
    }

**Comment by JohnCremona** [comment]
OK, but (as with so many Sage doctests) the test runs were written as illustrations of certain interactive programs, in which one would actually want to see the output.  It would certainly be better to have a test suite which was much more comprehensive and tested for f.p. results being within some range, with no output unless something is wrong; and a separate set of test programs with expected output, without "make check" testing for literal equality.  I just have other priorities.

**Comment by JohnCremona** [comment]
I would like to know if v20180710 addresses this issue, in which case it can be closed?

**Comment by SnarkBoojum** [comment]
I'll first update my package, then upload it, then the Debian build bot will compile it -- at that point we'll know!

**Comment by JohnCremona** [comment]
See also Issue #41

**Comment by SnarkBoojum** [comment]
Still failing on i386:
```
Testing d2...
14c14
< height = 13.56542070028558713
---
> height = 13.565420700285587132
16c16
< height = 27.13084140057117426
---
> height = 27.130841400571174263
Makefile:1297: recipe for target 'check_qrank' failed
```

**Comment by SnarkBoojum** [comment]
Ok, I disabled running tests on i386, but I'm still building the package (it's one of the official ports, after all!).
