### ISSUE TITLE
sieve_search.cc:818: suspicious expression ?

### ISSUE THREAD

**Issue by dcb314** [JohnCremona/eclib#44]
sieve_search.cc:818]: (style) Boolean result is used in bitwise operation. Clarify expression with parentheses.

Source code is

     if(!use_odd_nums && !b&1)

Maybe better code

     if(!use_odd_nums && !(b & 1))

**Comment by JohnCremona** [comment]
Fixed in 641ca8a62a8036fcbcff65202ea6fd0c438a942e
