### ISSUE TITLE
configure.ac depends on AX_PTHREAD

### ISSUE THREAD

**Issue by jdemeyer** [JohnCremona/eclib#48]
While running `./configure`, I get
```
./configure: line 18979: AX_PTHREAD: command not found
```
Indeed, it is using `AX_PTHREAD` in `configure.ac` but it's not shipping the custom m4 file containing a definition of the `AX_PTHREAD` macro.

**Comment by jdemeyer** [comment]
Note that this is not a fatal error: `configure` just continues anyway.

**Comment by JohnCremona** [comment]
I added this file in the branch ax_pthread.  If that makes the problem go away I'll merge it into the master branch.

**Comment by jdemeyer** [comment]
Fixed by #49
