### ISSUE TITLE
respect docdir in configure

### ISSUE THREAD

**Issue by kiwifb** [JohnCremona/eclib#54]
This is a very minor nitpick. The first line of the file `doc/Makefile.am` is
```
docdir = $(datadir)/doc/@PACKAGE@
```
First of it is the default - all right there could be a subtle difference, but it usually turns out to be the default
```
 Fine tuning of the installation directories:
  --bindir=DIR            user executables [EPREFIX/bin]
  --sbindir=DIR           system admin executables [EPREFIX/sbin]
  --libexecdir=DIR        program executables [EPREFIX/libexec]
  --sysconfdir=DIR        read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR    modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR     modifiable single-machine data [PREFIX/var]
  --libdir=DIR            object code libraries [EPREFIX/lib]
  --includedir=DIR        C header files [PREFIX/include]
  --oldincludedir=DIR     C header files for non-gcc [/usr/include]
  --datarootdir=DIR       read-only arch.-independent data root [PREFIX/share]
  --datadir=DIR           read-only architecture-independent data [DATAROOTDIR]
  --infodir=DIR           info documentation [DATAROOTDIR/info]
  --localedir=DIR         locale-dependent data [DATAROOTDIR/locale]
  --mandir=DIR            man documentation [DATAROOTDIR/man]
  --docdir=DIR            documentation root [DATAROOTDIR/doc/eclib]
  --htmldir=DIR           html documentation [DOCDIR]
  --dvidir=DIR            dvi documentation [DOCDIR]
  --pdfdir=DIR            pdf documentation [DOCDIR]
  --psdir=DIR             ps documentation [DOCDIR]
```
So why is it an issue? Because it is defined in `Makefile.am` any `--docdir=` argument passed to configure is ignored. Most distros have their documentation installation scheme and have default for docdir that may be different from autotools default.

Removing that line is all that is needed to fix this issue.

**Comment by JohnCremona** [comment]
I am happy to delete that line.  I don't want to make a new release with just that change though as 20190226 is almost accepted in Sage now.

**Comment by kiwifb** [comment]
I completely agree, this is a really minor nitpick and it doesn't justify a release. It was just picked up by Gentoo automated QA checks which pushed me to investigate.
