### ISSUE TITLE
version discovery

### ISSUE THREAD

**Issue by dimpase** [JohnCremona/eclib#56]
it seems to be tricky do discover the installed version of eclib, and this is exacly what we need to do on https://trac.sagemath.org/ticket/28333 (which is a part of https://trac.sagemath.org/ticket/27330).

Would you consider e.g. adding a pkg-config support, or a function that, unlike `show_version()`, prints something machine-readable (something using a template filled by running ./configure)?

**Comment by dimpase** [comment]
I've ended up trying the current Debian eclib (which is version v2018something) with Sage 8.9.beta5, getting an error in buildind `libs/eclib/wrap.cc`, and figuring out that the following doesn't compile on Debian eclib:
```C++
#include <eclib/interface.h>
void tst(long n)
{
set_bit_precision(n);
return;
}
```
but does with the needed eclib. I'll use it on https://trac.sagemath.org/ticket/28333 - but this is a hassle avoidable with, say, pkg-config...

**Comment by JohnCremona** [comment]
The version number is in the name of the source tarball in upstream/.  What
is that you cannot find?  The latest release is v20190226.  there have been
a few bugfixes since then, not in anything currently used by Sage except
perhaps commit f87108a (increased default PARI stack size to 10^9 bytes
(was only 100k)).

I don't know what you mean by pkg-config support.  If you want to make a
change in Sage, including the way Sage builds eclib, do it -- you don't
need me.  If you want eclib itself to change in some way, say so (and
preferably make a Pull Request through github).

John

**Comment by dimpase** [comment]
There is no source tarball to check. Namely, imagine you're on a Debian/Ubuntu system, and did
```
$ sudo apt install libec-dev
```
This gives you eclib headers and `libec.so`, but no easy OS-independent way to figure out the version of eclib you have (e.g. on Debian 10 one gets `20180815-2`, which is probably Debian's minor variation of `v20180815`, but this info can only be found  in an OS-dependent way, e.g. using apt on Debian). Now you want to use this eclib with some application (e.g. Sage), but you know that you
need at least `v2019xyz`. With (not yet existent) pkg-config support for eclib, one would do something like
```
$ pkg-config --modversion eclib
20180815
```
(there is also an autconf macro to use to so this check, so you can also do this version test in your `configure.ac` in just one line).

**Comment by dimpase** [comment]
E.g. `mpfr` supports pkg-config:
```
$ pkg-config --modversion mpfr
4.0.2
```
In fact, already Sage 8.8 may be built with system (or otherwise globally installed, e.g. into `/usr/local`)
version of `mpfr`.

I'll send you a PR to add such support for eclib.

**Comment by JohnCremona** [comment]
OK, I had not noticed that the email I received came from this github repository and had assumed wrongly that you were emailling me with a Sage issue.  Feel free to make a PR.

**Comment by JohnCremona** [comment]
To help with 
https://trac.sagemath.org/ticket/28454
I have made a lot of changes and am close to being ready for a new release.  Now would be a good time to add this.  If I understand correctly all I need to do is add one line to configure.ac?

**Comment by dimpase** [comment]
you mean, w.r.t. pkg-config? it's a bit more than 1 line, if you could wait until tomorrow, I'll send you a PR with it.

**Comment by dimpase** [comment]
it's 1 liner in configure.ac of a project using eclib to check the version, once pkg-config support is enabled, but a bit more for the latter.

**Comment by JohnCremona** [comment]
I can wait.  Thanks.

**Comment by dimpase** [comment]
see https://github.com/JohnCremona/eclib/pull/58
