### ISSUE TITLE
Missing default in a switch makes compiler itchy

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/eclib#61]
While having a look at the compilation of eclib (trying to know why I have problems on armel and armhf), I noticed a warning fly by: in libsrc/interface.cc, the longify function is seen by the compiler as not calling return.

Inspection shows there are several implementations ; they have in common a switch on a value without default clause : a potential silent problem arising if it started to have a new possible value.

I'll provide a patch soon.

**Comment by SnarkBoojum** [comment]
[clearer_longify.txt](https://github.com/JohnCremona/eclib/files/4029267/clearer_longify.txt)

**Comment by JohnCremona** [comment]
Thanks for this.  In fact one of the last commits I made was to keep lgtm happy with this function, but you are right that there are some missing defaults.  But your patch adds 3 defaults, whereas I see only two places where a new one is needed (for the switches on lines 342 and 354) as the switch on line 313 already has a default.

If you agree I'll add the two missing defaults.

**Comment by JohnCremona** [comment]
@SnarkBoojum Can we close this now?  Or do you need a new release?  The other changes since the 20190909 release are only minor tweaks to the config system and changing some default parameters in end programs probably only used by me.

**Comment by SnarkBoojum** [comment]
Yes, no need for a new release. Thanks!
