### ISSUE TITLE
allow mwrank to report the version

### ISSUE THREAD

**Issue by dimpase** [JohnCremona/eclib#67]
introduce `mwrank -v` (or `-V` ?) and let it print the version (hopefully the same as eclib used with it).

**Comment by JohnCremona** [comment]
mwrank already has a command-line parameter -v whichis used to set verbosity level, so I don't want to change that.  I'll see if I can get mwrank --version to do what you suggest.  It will output a string such as 'v20210310' for the eclib version.

**Comment by dimpase** [comment]
all the other parameters are 1-letter, I'd use `-V` for version (this is one of several possible conventions, IMHO).

**Comment by JohnCremona** [comment]
OK, I went for -V.  New version up after some more testing, but I won't put a new tag on it yet since there are bound to be more tweaks.
