### ISSUE TITLE
Compilation fails with C++11

### ISSUE THREAD

**Issue by nqn76** [JohnCremona/eclib#8]
mmatrix.cc: In function 'long int nullity(const mat_m&)':
mmatrix.cc:782:18: error: reference to 'rank' is ambiguous
  return ncols(m)-rank(m);

It looks like rank is already a thing in c++11:
http://en.cppreference.com/w/cpp/types/rank

**Comment by JohnCremona** [comment]
Thanks for pointing this out.  I'll change from having a function rank() to using a class method.
Do you know how to check code for C++11 compliance?  I only use gcc, currently version 4.8.2.

**Comment by JohnCremona** [comment]
I am fixing the issue now.

**Comment by JohnCremona** [comment]
If the current version has solved the problem (as I hope it has) could you please let me know?

**Comment by nqn76** [comment]
Everything works OK with the latest version, thank you
